sudo: false

language: node_js
node_js:  "14.13.1"
cache: 
  directories:
  - node_modules
before_script:
  - cd frontend && npm install
  - cd ../backend && npm install
  - cd ..
script:
  - npm test
